apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h53c6oqat-go
  janus-idp.io/tekton: h53c6oqat-go
  backstage.io/kubernetes-id: h53c6oqat-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h53c6oqat-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
