apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: h53c6oqat-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: h53c6oqat-go 
  name: h53c6oqat-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: h53c6oqat-go 
